# Generated by Django 5.1.3 on 2024-11-19 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='key',
            new_name='access_key_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='access_key_secret',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
