# Generated by Django 5.1.3 on 2024-11-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100)),
                ('instance_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('network_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cloud_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudServerApp.cloudserver')),
            ],
        ),
    ]
